name = "codinfox-zola"
description = "Codinfox theme for Zola"
license = "MIT"
homepage = "https://github.com/svavs/codinfox-zola"
min_version = "0.11.0"
demo = "https://codinfox-zola.vercel.app/"

[author]
name = "Silvano Sallese"
homepage = "https://svavs.github.io/"

[original]
author =  "Li Zhihao"
homepage = "http://codinfox.github.io"
repo = "https://github.com/codinfox/codinfox-lanyon"

[extra]

